### PR TITLE
Added product_id to FinTS Login

### PR DESCRIPTION
**Pull request by pgruener**
The newer version of python-fints doesnt provide a default ID anymore to get the data.
So therefore each company needs to acquire its own ID, like this is noted on: https://python-fints.readthedocs.io/en/latest/upgrading_3_4.html

This PR enables the "FinTS Login" DocType to get the acquired product_id maintained and makes use of it during connection establishment.

By changing the doctype, my installation removed all the defaults in the "Fints Login" doctypes json.. I don't know if this is a new or old default. I could keep the defaults if needed.

### CODE REVIEW

**Comment by barredterra** [comment]
> By changing the doctype, my installation removed all the defaults in the "Fints Login" doctypes json.. I don't know if this is a new or old default. I could keep the defaults if needed.

Beginning with v13, frappe stores field definitions in this more compact form. So the question would be if this app still wants to support v12 or if there should be new branches for v13 and v14 etc.

**Comment by pgruener** [comment]
> > By changing the doctype, my installation removed all the defaults in the "Fints Login" doctypes json.. I don't know if this is a new or old default. I could keep the defaults if needed.
> 
> Beginning with v13, frappe stores field definitions in this more compact form. So the question would be if this app still wants to support v12 or if there should be new branches for v13 and v14 etc.

Ok thanks for the background.

I'd expect, to get a quicker merge approval, I'd change it to be v12 compatible ;-)

**Comment by jHetzer** [comment]
@pgruener: thank you for your PR

@barredterra I think it would be reasonable to drop v12 support as the version is EOL. I will let you handle this PR. You are more up to date.
https://github.com/frappe/erpnext/wiki/Supported-Versions

**Comment by jHetzer** [comment]
Maybe you should also change the requirements.txt to fints=4.* so breaking changes won't affect the app

**Comment by barredterra** [comment]
@jHetzer I cannot properly review this, since I'm not using the app and don't have a test environment. But the effective one-line-change looks fine to me.

**Comment by pgruener** [comment]
> Maybe we should also change the requirements.txt to fints=4.* so breaking changes won't affect the app

I didn't want to enforce that break for all other users, which still rely on an older version. This is also why I didn't mark the new property to be mandatory. 
In this current way I expect it will work for all (but v12 now ;-))
Thanks for the quick merge!

**Pull request merged**
