### PR TITLE
refactor: import_payment.py

### PR DESCRIPTION
**Pull request by barredterra**
Thanks for your work! I took the freedom to shuffle your code around a little bit to achieve the following goals:

* Better readability.
* Better performance: continue the loop as early as possible.
* Better security: use `frappe.get_list()` instead of raw SQL.

As I'm new to this topic, I hope I didn't misunderstand the logic. I wasn't able to test this yet – please use with care.

### CODE REVIEW

**Comment by jHetzer** [comment]
Thank you very much. I like your improvements but there are some problems.
Could you allow me to push to your branch to commit the fixes:
image

**Comment by barredterra** [comment]
image
Done :heavy_check_mark:

**Comment by jHetzer** [comment]
Unfortunately the setting did not work (as expected) and I created a PR in your fork https://github.com/alyf-de/erpnextfints/pull/1

**Comment by barredterra** [comment]
Thanks, merged your PR :)

**Pull request merged**
